gliff-ai/manage

.github/workflows/azure-static-web-apps-ambitious-pond-0d3b89503.yml, package-lock.json
Same as https://github.com/gliff-ai/annotate/pull/123
Does dependabot, skips deploys for it
=> Dependabot

examples/src/index.tsx, package.json, src/api.ts, src/hooks/use-auth.tsx, src/index.tsx, src/views/ProjectsView.tsx, src/views/UsersView.tsx
Update and fetch the list of projects when adding one.
Also allow fetching of projects without an API key
Invite a new user. Most of the gory details are handled elsewhere, this is just a form to make the request.
=> Fix get project

examples/src/index.tsx, package.json, src/api.ts, src/hooks/use-auth.tsx, src/index.tsx, src/interfaces.ts, src/views/ProjectsView.tsx, src/views/UsersView.tsx, webpack.config.js
- Fix showing team members
- Show pending invites
- Tidy up
- Can invite users to collections (requires API update)
=> Show Team and Invites

.gitignore, package-lock.json, package.json, src/components/InvitePopover.tsx, src/views/ProjectsView.tsx, src/views/UsersView.tsx
Replace html elements with material-ui elements.
Adds:
```
"dependencies": {
"@material-ui/core": "^4.11.3",
"@material-ui/icons": "^4.11.2",
```
No
No
=> chore: Apply Material-UI

src/index.tsx
Currently the default page is blank, make it projects
=> fix: default page is projects

src/views/UsersView.tsx
Very minor change that makes the invites actually work.
Also, removes an empty file.
None
None
None
N/A
=> fix: make team invites work

package-lock.json, package.json, src/components/PageSelector.tsx, src/views/ProjectsView.tsx, src/views/TeamView.tsx
Make text readable by not using green on white  for text. 
Updated to the latest: "@gliff-ai/style": "^0.5.1",
N/A
N/A
N/A
N/A
=> Fix hard to read text

package-lock.json, package.json, src/components/PageSelector.tsx
=> build: update gliff-ai STYLE

examples/index.tsx, src/components/InviteDialog.tsx, src/interfaces.ts, src/views/ProjectsView.tsx, src/views/TeamView.tsx
- fix: invite dialog
Invite Autocomplete select never changed so you couldn't invite anyone other than user 1 (or trusted service 1)
=> Fix Invite Dialog

examples/index.tsx, src/components/PageSelector.tsx, src/hooks/use-auth.tsx, src/index.tsx, src/interfaces.ts, src/views/CollaboratorsView.tsx, src/views/ProjectsView.tsx, src/views/TeamView.tsx, src/views/TrustedServiceView.tsx
Non-owners can only view and open projects they have been added to.
No
No
No
=> feat: Make some views 'owners-only'

package-lock.json, package.json
=> build: fix react router just in case

.github/workflows/codeql-analysis.yml
=> ci: make codeQL look at TS not JS

package-lock.json, package.json
All the minor dependabots, scripted PR
=> build(deps): dependabot batch

examples/index.tsx, src/components/PageSelector.tsx, src/index.tsx, src/interfaces.ts
=> feat: hide TrustedServices page for free accounts

examples/index.tsx, package-lock.json, package.json, src/views/CollaboratorsView.tsx, src/views/ProjectsView.tsx, src/views/TeamView.tsx, src/views/TrustedServiceView.tsx
Will be more apparent when hooked up to a slow API, but adds spinners to the 4 main pages.
Changes the default user to an owner to show all pages on Azure/Percy etc
=> fix: loading spinners

src/index.tsx
=> fix: App doesn't re-render when user prop changes

.github/workflows/automate.yml, __tests__/e2e/index.test.js, package-lock.json, package.json
- Update harness to support iPad
- Change GH action to use new host/ports
=> feat: browser tests

package-lock.json
=> fix: Percy screenshot sizes

examples/samples.ts, src/components/PageSelector.tsx, src/index.test.tsx, src/index.tsx, src/interfaces.ts, src/views/CollaboratorsView.tsx, src/views/ProjectsView.tsx, src/views/TeamView.tsx, src/views/TrustedServiceView.tsx
Add access for team members: the `userAccess` prop replaces `isOwner`.
No
Yes, fixed tests on access.
No
=> feat: Access for members

src/views/ProjectsView.tsx
as it says on the tin.
no
no
no
no
=> fix: DOMINATE-55

__tests__/e2e/index.test.js, examples/index.tsx, examples/samples.ts, src/components/CreateProjectDialog.tsx, src/components/ProgressBar.tsx, src/components/index.ts, src/index.test.tsx, src/index.tsx, src/interfaces.ts, src/views/ProjectsView.tsx
Add a progress bar to the "Projects" page to show progress in the annotation, for each project, as the number of completed annotations over the number of assigned images. For projects that include only unassigned images the message "No assigned images." is displayed instead.
no
no
no
=> feat: Add progress bar

.github/dependabot.yml, .github/labeler.yml, .github/workflows/add-to-project.yml, .github/workflows/bot-automerge.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependency-minor-batch.yml, .github/workflows/lint-build-test.yml, .github/workflows/pr-title-labeler.yml
=> feat: add updated github actions

package-lock.json, package.json, src/index.tsx
Bump to stable. Nothing breaking here.
=> chore: Bump react router

vite.config.ts
fix bug that prevents the app from loading.
=> fix: Module 'hoist-non-react-statics' does not provide export named 'default'

src/components/ProgressBar.tsx, src/views/ProjectsView.tsx
=> fix: Overlapping text

package-lock.json, package.json, src/components/plugins/AddPluginDialog.tsx
Just a little tweak of the text when adding plugins
@joshuajames-smith you may want to make it nicer?
=> fix: tweak copy for adding plugin

package-lock.json, package.json
Turns out we updated the devDep but not the peerDep for the STYLE 9->13 upgrade this morning. This fixes that and runs `npm update`.
=> fix: update STYLE peer dependency too

package-lock.json, package.json, src/components/plugins/AddPluginDialog.tsx, src/components/plugins/DeletePluginDialog.tsx, src/components/plugins/EditPluginDialog.tsx, src/components/plugins/ProjectsAutocomplete.tsx, src/components/projects/CreateProjectDialog.tsx, src/components/projects/EditProjectDialog.tsx, src/views/ProjectsView.tsx
Use the latest components like Button, Dialogue from STYLE
We need to merge in https://github.com/gliff-ai/style/pull/255 for some of the changes to the buttons to take effect.r
Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!
=> feat: Bring manage upto date with styles

src/components/projects/CreateProjectDialog.tsx
Change the name of the Dialogue to "Create Project" 
Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!
=> fix: change Dialogue name
